### ISSUE TITLE
Deliver successfully submits app in AppStore. But think that there was a failure

### ISSUE THREAD

**Issue by PaulTaykalo** [fastlane/deliver#124]
So `deliver` actually succeeds. But it thinks that there was a failure

fastlane 0.1.14
deliver 0.7.12  

```
DEBUG [2015-03-03 00:44:31.30]: [Transporter Output]: DBG-X: Returning 0
ERROR [2015-03-03 00:44:31.38]: An exception has occurred: Scheduling automatic restart in 1 minute
INFO [2015-03-03 00:44:31.39]: Variable Dump:
INFO [2015-03-03 00:44:31.39]: {:LANE_NAME=>:deploy, :CERT_FILE_PATH=>"/tmp/fastlane_core/123123-23232.cer", :CERT_CERTIFICATE_ID=>"12312312", :SIGH_PROFILE_PATH=>"/Volumes/data/Projects/MyProject-ios/Distribution_com.ids.MyProject.mobileprovision", :SIGH_UDID=>"232323-232323-232323-b92323200-12ceec2fe26e", :IPA_OUTPUT_PATH=>"/Volumes/data/Projects/MyProject-ios/MyProject.ipa", :DSYM_OUTPUT_PATH=>"/Volumes/data/Projects/MyProject-ios/MyProject.app.dSYM.zip"}
FATAL [2015-03-03 00:44:31.39]: Error uploading ipa file
FATAL [2015-03-03 00:44:31.39]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliver_process.rb:263:in `trigger_ipa_upload': Error uploading ipa file (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliver_process.rb:54:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliverer.rb:132:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliverer.rb:84:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliverer.rb:84:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/actions/deliver.rb:18:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/actions/deliver.rb:18:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/actions/deliver.rb:16:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/actions/deliver.rb:16:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:83:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/actions/actions_helper.rb:28:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:82:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:81:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/fast_file.rb:81:in `method_missing'
	from (eval):49:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/runner.rb:16:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/runner.rb:16:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/runner.rb:10:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/runner.rb:10:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/lane_manager.rb:15:in `block in cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/lane_manager.rb:14:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/lib/fastlane/lane_manager.rb:14:in `cruise_lanes'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/bin/fastlane:30:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/bin/fastlane:58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/bin/fastlane:62:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

Lane from Fastfile  
```
lane :deploy do
  cert
  sigh

  ipa({
    workspace: "MyProject.xcworkspace",
    configuration: "Release",
    scheme: "MyProject",
    identity: "iPhone Distribution: Ivan Ivanov(adfasfsaF)",
    embed: Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH],
    verbose: "true"
  })
  deliver :skip_deploy, :force
end
```

Deliver file  
```
screenshots_path "./screenshots/"
version '1.6.3' # you can pass this if you want to verify the version number with the ipa file
config_json_folder './deliver'
ipa "./../MyProject.ipa" # this can be used instead of the `do` block, if you prefer manually building the ipa file
success do
  # system("say 'Successfully deployed a new version.'")
end
```

**Comment by KrauseFx** [comment]
I think this is related to https://github.com/KrauseFx/deliver/issues/44, right?

**Comment by PaulTaykalo** [comment]
It seems so. The original #44 was about some WiFi issues, so I thought it was different one.  but yep. It seems that they are related. Maybe even the same.

**Comment by edwardlafoy** [comment]
I'm experiencing the same issue - uploaded successfully to iTunesConnect but spit out a RunTime error:

```
/Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliver_process.rb:263:in `trigger_ipa_upload': [31mError uploading ipa file[0m (RuntimeError)
	from /Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliver_process.rb:54:in `run'
	from /Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliverer.rb:132:in `finished_executing_deliver_file'
```

**Comment by silvansky** [comment]
Got the same issue. And also iTC Prerelease tab says that build is in "Processing" state for hours, so I'm not sure this build was really successful.

**Comment by edwardlafoy** [comment]
@KrauseFx 

This is killing our CI server at least once a day at this point...

	[35mDEBUG [2015-03-11 15:45:47.15]: [0m[Transporter Output]: INFO: Done performing uploadDone  notification to Apple.
	[35mDEBUG [2015-03-11 15:45:47.15]: [0m[Transporter Output]: INFO: The package: /Users/mobileci/.jenkins/jobs/Fedtrak/workspace/fastlane/./965861755.itmsp has been successfully uploaded.
	[37mINFO [2015-03-11 15:45:47.34]: [0m[32miTunes Transporter successfully finished its job[0m
	[35mDEBUG [2015-03-11 15:45:47.34]: [0m[Transporter Output]: DBG-X: Returning 0
	[31mERROR [2015-03-11 15:45:47.42]: [0mAn exception has occurred: Scheduling automatic restart in 1 minute
	[37mINFO [2015-03-11 15:45:47.42]: [0m[33mVariable Dump:[0m /Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliver_process.rb:237:in `trigger_metadata_upload': [31mError uploading app metadata[0m (RuntimeError)
	from /Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliver_process.rb:50:in `run'
	from /Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliverer.rb:132:in `finished_executing_deliver_file'
	from /Users/mobileci/.rvm/gems/ruby-2.2.0/gems/deliver-0.7.12/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'

**Comment by HughJeffner** [comment]
I added some logs in #44, they seem to match what I see here

**Comment by dral3x** [comment]
Got the same issue here.

I don't understand why the logs of transporter is more important than its return value.
If the transporter command return 0, deliver should succeded ignoring what the logs said.

Am I missing something?
Thanks!

```
DEBUG [2015-03-16 14:55:53.50]: [Transporter Output]: INFO: Done performing uploadDone notification to Apple.
DEBUG [2015-03-16 14:55:53.50]: [Transporter Output]: INFO: The package: /tmp/976166831.itmsp has been successfully uploaded.
INFO [2015-03-16 14:55:53.66]: iTunes Transporter successfully finished its job
DEBUG [2015-03-16 14:55:53.66]: [Transporter Output]: DBG-X: Returning 0
ERROR [2015-03-16 14:55:54.00]: An exception has occurred: Scheduling automatic restart in 1 minute
```
