### ISSUE TITLE
Empty version number

### ISSUE THREAD

**Issue by dral3x** [fastlane/deliver#254]
This morning I try to upload a new app and my fastlane (produce, deliver + slack) failed because the app version was not specified.

Maybe something is broken in the new version (I updated all gems this morning).
```
fastlane 1.6.0
deliver 0.12.1
produce 0.3.5
```

Full log
```
[09:46:07]: Driving the lane 'deploy'
[09:46:07]: ---------------------
[09:46:07]: --- Step: produce ---
[09:46:07]: ---------------------
[09:46:10]: Logging into iTunesConnect
[09:46:25]: Successfully logged into iTunesConnect
[09:46:37]: App '**hidden**' exists already, nothing to do on iTunes Connect
[09:46:49]: Found Apple ID 1014889073
[09:46:49]: ---------------------
[09:46:49]: --- Step: deliver ---
[09:46:49]: ---------------------
[09:46:49]: Set default language to en-US
[09:46:49]: Got all information needed to deploy a new update ('') for app 'com.spreaker.custom.app-36010'
[09:46:49]: Logging into iTunesConnect
[09:46:54]: Opening detail page for app 1014889073 - com.spreaker.custom.app-36010
[09:47:08]: Can not create version  on iTunesConnect. Maybe it was already created.
[09:47:08]: There is already a new version created, which does not match the current version: ''
[09:47:09]: Changed the version number of the latest version to ''
[09:47:09]: Going to download app metadata from iTunesConnect
[09:47:12]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
[09:47:12]: [Transporter]: INFO: Logging configured successfully.
[09:47:12]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.5]
[09:47:12]: [Transporter]: INFO: OS identifier: Mac OS X 10.10.3 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[09:47:12]: [Transporter]: INFO: Memory: [JVM] 27M free, 55M total, 910M max [System] (Physical) 5619M free, 16384M total (Swap) 0 free, 0 total
[09:47:12]: [Transporter]: INFO: LookupMetadata mode selected.
[09:47:12]: [Transporter]: INFO: Performing lookupMetadata request ...
[09:47:12]: [Transporter]: INFO: Looking up the metadata with the apple_id '1014889073' ...
[09:47:12]: [Transporter]: DBG-X: Memory: [JVM] 26M free, 55M total, 910M max [System] (Physical) 5619M free, 16384M total (Swap) 0 free, 0 total
[09:47:12]: [Transporter]: DBG-X: Memory: [JVM] 26M free, 55M total, 910M max [System] (Physical) 5619M free, 16384M total (Swap) 0 free, 0 total
[09:47:12]: [Transporter]: DBG-X: Using operation named: authenticateForSession
[09:47:12]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[09:47:12]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[09:47:12]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[09:47:12]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.3 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[09:47:12]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[09:47:12]: [Transporter]: DBG-X:   parameter TransporterArguments = -m lookupMetadata -u **hidden email** -p **hidden value** -apple_id 1014889073 -destination ./
[09:47:12]: [Transporter]: DBG-X:   parameter Username = **hidden email**
[09:47:12]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[09:47:12]: [Transporter]: INFO: id = 20150701094712-849
[09:47:14]: [Transporter]: DBG-X: Apple's web service operation return value:
[09:47:14]: [Transporter]: DBG-X:   parameter SessionId = CKOmDBIQ1Uwz07B6Sr62YAYADFidpQ==
[09:47:14]: [Transporter]: DBG-X:   parameter SharedSecret = 27b9b7c6-00fd-448e-902f-0d7db7a831ab
[09:47:14]: [Transporter]: DBG-X: Using operation named: lookupMetadataWithArguments
[09:47:14]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[09:47:14]: [Transporter]: DBG-X:   parameter AppleId = 1014889073
[09:47:14]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[09:47:14]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[09:47:14]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.3 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[09:47:14]: [Transporter]: DBG-X:   parameter TransporterArguments = -m lookupMetadata -u **hidden email** -p **hidden value** -apple_id 1014889073 -destination ./
[09:47:14]: [Transporter]: DBG-X:   parameter Username = **hidden email**
[09:47:14]: [Transporter]: DBG-X:   parameter VendorId = (null)
[09:47:14]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[09:47:14]: [Transporter]: INFO: id = 20150701094714-146
[09:47:14]: [Transporter]: DBG-X: Apple's web service operation return value:
[09:47:14]: [Transporter]: DBG-X:   parameter Success = true
[09:47:14]: [Transporter]: DBG-X: Inflated 1128 bytes to 2034
[09:47:14]: [Transporter]: INFO: Creating the stub package directory ...
[09:47:14]: [Transporter]: INFO: Created the stub package directory: /mnt/cache/worker-store-ios-application-publish-1/tmp_1435735343_8/fastlane/./1014889073.itmsp
[09:47:14]: [Transporter]: INFO: Writing out the metadata file ...
[09:47:14]: [Transporter]: INFO: Finished writing out the metadata file.
[09:47:14]: iTunes Transporter successfully finished its job
[09:47:14]: [Transporter]: DBG-X: Returning 0
[09:47:14]: Successfully downloaded the latest package from iTunesConnect.
[09:47:14]: Modifying version '1.4.1' of app com.spreaker.custom.app-36010
[09:47:14]: -------------------
[09:47:14]: --- Step: slack ---
[09:47:14]: -------------------
[09:47:15]: Successfully sent Slack notification
[09:47:15]: Variable Dump:
[09:47:15]: {:ENVIRONMENT=>nil, :PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :PRODUCE_APPLE_ID=>"1014889073"}
[09:47:15]: Version mismatch: on iTunesConnect the latest version is '1.4.1', you specified ''
[09:47:16]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/app_metadata.rb:81:in `verify_version': Version mismatch: on iTunesConnect the latest version is '1.4.1', you specified '' (RuntimeError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:211:in `verify_app_on_itunesconnect'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:38:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):40:in `block (2 levels) in parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:39:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:39:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:29:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:29:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/bin/fastlane:39:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/bin/fastlane:128:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.6.0/bin/fastlane:134:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

Fastfile
```
before_all do
  ENV["SLACK_URL"]='**hidden**'

  ENV["DELIVER_USER"]='**hidden**'
  ENV["DELIVER_PASSWORD"]='**hidden**'

end

lane :deploy do

  if ENV["CUSTOMAPP_APPLE_ID"].nil? || ENV["CUSTOMAPP_APPLE_ID"].empty?

    ENV["PRODUCE_SKIP_DEVCENTER"]="true"

    # It will create the app
    produce({
      produce_username:               ENV["DELIVER_USER"],
      produce_app_identifier:         "com.spreaker.custom.*",
      produce_app_identifier_suffix:  ENV["CUSTOMAPP_BUNDLE_SUFFIX"],
      produce_app_name:               ENV["CUSTOMAPP_NAME"],
      produce_language:               ENV["CUSTOMAPP_LANGUAGE"],
      produce_version:                ENV["CUSTOMAPP_VERSION"],
      produce_sku:                    ENV["CUSTOMAPP_SKU"]
    })

    # ENV["PRODUCE_APPLE_ID"] is now available

  else

    ENV["PRODUCE_APPLE_ID"] = ENV["CUSTOMAPP_APPLE_ID"]

  end

  # Upload all metadata and ipa file
  # :skip_deploy = don't send the build in "waiting for review" state
  deliver
end

after_all do |lane|

  # This block is called only if the executed lane was successful

  spreaker_uri = "https://**hidden**/" + ENV["CUSTOMAPP_ID"]
  itc_uri = "https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/" + ENV["PRODUCE_APPLE_ID"]

  slack({
    message: "Successfully deployed iOS Custom app " + ENV["CUSTOMAPP_ID"],
    success: true,
    channel: 'bot',
    payload: {
      'Spreaker backend link' => spreaker_uri,
      'iTunes Connect link' => itc_uri,
    },
    default_payloads: [], # No default payload
  })

end


error do |lane, exception|

  # This block is called only if the executed lane fail

  spreaker_uri = "https://**hidden**/" + ENV["CUSTOMAPP_ID"]
  itc_uri = "https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/" + ENV["PRODUCE_APPLE_ID"]
  error_msg = exception.message.to_s

  slack({
    message: "Failed to deploy iOS Custom app " + ENV["CUSTOMAPP_ID"],
    success: false,
    channel: 'bot',
    payload: {
      'Spreaker backend link' => spreaker_uri,
      'iTunes Connect link' => itc_uri,
      'Failure reason' => error_msg,
    },
    default_payloads: [], # No default payload
  })

end
```

Deliverfile
```
###################### App Metadata ######################

default_language ENV["CUSTOMAPP_CULTURE"]

apple_id ENV["PRODUCE_APPLE_ID"]

screenshots_path ENV["CUSTOMAPP_SCREENSHOTS_FOLDER"]

title ENV["CUSTOMAPP_NAME"]

description ENV["CUSTOMAPP_DESCRIPTION"]

if (ENV["CUSTOMAPP_CHANGELOG"] != nil)
  changelog ENV["CUSTOMAPP_CHANGELOG"]
end

keywords ENV["CUSTOMAPP_KEYWORDS"].split(',')

support_url "https://www.spreaker.com/help"

privacy_url "https://www.spreaker.com/privacy"

app_icon ENV["CUSTOMAPP_ICON_FILE"]

primary_category ENV["CUSTOMAPP_CATEGORY"]

ratings_config_path ENV["CUSTOMAPP_RATINGS_FILE"]

copyright "#{Time.now.year} Spreaker Inc."

app_review_information({
  first_name:     "**hidden**",
  last_name:      "**hidden**",
  phone_number:   "**hidden**",
  email_address:  "**hidden**",
  demo_user:      "**hidden**",
  demo_password:  "**hidden**"
})

automatic_release true

price_tier 0

submit_further_information({
  export_compliance: {
    encryption_updated: false,
    cryptography_enabled: false,
    is_exempt: false
  },
  third_party_content: {
    contains_third_party_content: false,
    has_rights: false
  },
  advertising_identifier: false
})

skip_pdf true

###################### App IPA ######################

ipa ENV["CUSTOMAPP_IPA_FILE"]
```

.env
```
CUSTOMAPP_ID="36010"
CUSTOMAPP_BUNDLE_SUFFIX="app-36010"
CUSTOMAPP_SKU="CUSTOMAPP_36010"
CUSTOMAPP_VERSION="1.4.1"
CUSTOMAPP_LANGUAGE="English"
CUSTOMAPP_CULTURE="en-US"
CUSTOMAPP_NAME="**hidden**"
CUSTOMAPP_DESCRIPTION="**hidden**"
CUSTOMAPP_KEYWORDS="**hidden**"
CUSTOMAPP_CATEGORY="Entertainment"
CUSTOMAPP_IPA_FILE="/mnt/cache/worker-store-ios-application-publish-1/tmp_1435735343_8/CustomApp-36010.ipa"
CUSTOMAPP_ICON_FILE="/mnt/cache/worker-store-ios-application-publish-1/tmp_1435735343_8/store_icon_959654615735.png"
CUSTOMAPP_SCREENSHOTS_FOLDER="/mnt/cache/worker-store-ios-application-publish-1/tmp_1435735343_8/fastlane/screenshots"
CUSTOMAPP_RATINGS_FILE="/mnt/cache/worker-store-ios-application-publish-1/tmp_1435735343_8/fastlane/ratings.json"
CUSTOMAPP_APPLE_ID_OUTFILE="/mnt/cache/worker-store-ios-application-publish-1/tmp_1435735343_8/fastlane/apple_id.txt"
```

**Comment by KrauseFx** [comment]
Have you tried specifying the `version` in your `Deliverfile`?

**Comment by dral3x** [comment]
With that, I resolved. But before the update, the version number was taken
automatically from the ipa (as it should do also now) but it does not

**Comment by KrauseFx** [comment]
That's odd, did you change anything on your side? 

That's code `deliver` uses: 
```ruby
# Fetches the app identifier (e.g. com.facebook.Facebook) from the given ipa file.
    def self.fetch_app_identifier(path)
      plist = IpaFileAnalyser.fetch_info_plist_file(path)
      return plist['CFBundleIdentifier'] if plist
      return nil
    end

    # Fetches the app version from the given ipa file.
    def self.fetch_app_version(path)
      plist = IpaFileAnalyser.fetch_info_plist_file(path)
      return plist['CFBundleShortVersionString'] if plist
      return nil
    end

    def self.fetch_info_plist_file(path)
      Zip::File.open(path) do |zipfile|
        zipfile.each do |file|
          if file.name.include?'.plist' and not ['.bundle', '.framework'].any? { |a| file.name.include?a }
            # We can not be completely sure, that's the correct plist file, so we have to try
            begin
              # The XML file has to be properly unpacked first
              tmp_path = "/tmp/deploytmp.plist"
              File.write(tmp_path, zipfile.read(file))
              system("plutil -convert xml1 #{tmp_path}")
              result = Plist::parse_xml(tmp_path)
              File.delete(tmp_path)

              if result['CFBundleIdentifier'] or result['CFBundleVersion']
                return result
              end
            rescue
              # We don't really care, look for another XML file
            end
          end
        end
      end

      nil
    end
```

**Comment by dral3x** [comment]
No. The app is build the same way. The script is always the same. I just
updated fastlane (and other gems) to try to fix an issue that was related
to iTunes connect (it was rejecting the app metadata).
After 4 hours, the app has been accepted but I had to put version
information inside deliver file.

No more clue.

Il lunedì 6 luglio 2015, Felix Krause <notifications@github.com> ha scritto:

> That's odd, did you change anything on your side?
>
> That's code deliver uses:
>
> # Fetches the app identifier (e.g. com.facebook.Facebook) from the given ipa file.
>     def self.fetch_app_identifier(path)
>       plist = IpaFileAnalyser.fetch_info_plist_file(path)
>       return plist['CFBundleIdentifier'] if plist
>       return nil
>     end
>
>     # Fetches the app version from the given ipa file.
>     def self.fetch_app_version(path)
>       plist = IpaFileAnalyser.fetch_info_plist_file(path)
>       return plist['CFBundleShortVersionString'] if plist
>       return nil
>     end
>
>     def self.fetch_info_plist_file(path)
>       Zip::File.open(path) do |zipfile|
>         zipfile.each do |file|
>           if file.name.include?'.plist' and not ['.bundle', '.framework'].any? { |a| file.name.include?a }
>             # We can not be completely sure, that's the correct plist file, so we have to try
>             begin
>               # The XML file has to be properly unpacked first
>               tmp_path = "/tmp/deploytmp.plist"
>               File.write(tmp_path, zipfile.read(file))
>               system("plutil -convert xml1 #{tmp_path}")
>               result = Plist::parse_xml(tmp_path)
>               File.delete(tmp_path)
>
>               if result['CFBundleIdentifier'] or result['CFBundleVersion']
>                 return result
>               end
>             rescue
>               # We don't really care, look for another XML file
>             end
>           end
>         end
>       end
>
>       nil
>     end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KrauseFx/deliver/issues/254#issuecomment-118908948>.
>


-- 
Alessandro Calzavara
http://about.me/alessandro.calzavara
