### ISSUE TITLE
can't upload + build blocked in "Created" status

### ISSUE THREAD

**Issue by frranck** [fastlane/deliver#261]
Hello,
since yesterday i'm getting some error in deliver:

```
[10:44:52]: Transporter transfer failed.
[10:44:52]:
[10:44:52]:
[10:44:52]: Return status of iTunes Transporter was 1:
[10:44:52]: Return status of iTunes Transporter was 1:
/Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:385:in `trigger_ipa_upload': Error uploading ipa file (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:51:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:51:in `block in run_deliver'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:47:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:47:in `run_deliver'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:121:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/bin/deliver:137:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'
```

Then the build stays in "Created" status in itunesconnect

**Comment by camdenfullmer** [comment]
+1

**Comment by KrauseFx** [comment]
Could you share a bit more of your transporter output? There should be another error message above.

**Comment by KrauseFx** [comment]
Any updates on this?
