### ISSUE TITLE
upload_metadata still verifies the ipa file

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/deliver#264]

**Comment by KrauseFx** [comment]
```
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliverfile/dsl.rb:134:in `validate_ipa!': The given ipa file seems to be wrong. Make sure it's a valid ipa file. (Deliver::Deliverfile::Deliverfile::DSL::DeliverfileDSLError)
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:179:in `fetch_information_from_ipa_file'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:29:in `run'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:51:in `new'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:51:in `block in run_deliver'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:47:in `chdir'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:47:in `run_deliver'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:41:in `block (2 levels) in run'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:121:in `run'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/gems/deliver-0.12.1/bin/deliver:137:in `<top (required)>'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/bin/deliver:23:in `load'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/bin/deliver:23:in `<main>'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	from /Users/felixkrause/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```
