### ISSUE TITLE
Made for kids content rating not working

### ISSUE THREAD

**Issue by robwithhair** [fastlane/deliver#274]
It seems that if you put made for kids to 1 in ratings.json it doesn't seem to build correctly but if it's set to 0 then it does.  Error screenshot shows the content ratings page open with everything checked apart from the made for kids, which the checkbox is checked but the dropdown is not selected correctly.  I have attempted to build with made for kids set to 0 to see if this indeed works fine, and it does.  The error message is deceptive but the screenshots seem to show made for kids to be the culprit.

**Comment by robwithhair** [comment]
```
[37m[12:16:13]: [0m[32mSuccessfully saved review information[0m
[37m[12:16:13]: [0mOpening detail page for app 955814004 - com.AppInstitute.healthye
[37m[12:16:23]: [0m[32mUpdating the app's rating[0m
[37m[12:16:24]: [0m[32mSetting 'Cartoon or Fantasy Violence' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Realistic Violence' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Prolonged Graphic or Sadistic Violence' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Profanity or Crude Humor' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Mature/Suggestive Themes' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Horror/Fear Themes' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Medical/Treatment Information' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Alcohol, Tobacco, or Drug Use or References' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Simulated Gambling' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Sexual Content or Nudity' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Graphic Sexual Content and Nudity' to NONE.[0m
[37m[12:16:24]: [0m[32mSetting 'Unrestricted Web Access' to NO.[0m
[37m[12:16:24]: [0m[32mSetting 'Gambling and Contests' to NO.[0m
[37m[12:16:24]: [0m[32mSetting kids mode to 1[0m
[33m[12:16:24]: [0mCouldn't set kids mode because of other options.
[37m[12:16:24]: [0mFinished setting updated app rating
[37m[12:16:28]: [0m[32mRemoving alpha channel from provided App Icon (iTunes Connect requirement)[0m
[37m[12:16:28]: [0mOpening detail page for app 955814004 - com.AppInstitute.healthye
LSOpenURLsWithRole() failed with error -600 for the file /Users/robwithhair/jenkins_slave/workspace/iOS Build - Release Automation/iOS/fastlane/Error1437391080.png.
[37m[12:18:01]: [0m[33mVariable Dump:[0m
[37m[12:18:01]: [0m{:ENVIRONMENT=>nil, :PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :BUILD_NUMBER=>0, :PRODUCE_APPLE_ID=>"955814004", :CERT_FILE_PATH=>"./3LMSG3CHK3.cer", :CERT_CERTIFICATE_ID=>"3LMSG3CHK3", :SIGH_PROFILE_PATH=>"/Users/robwithhair/jenkins_slave/workspace/iOS Build - Release Automation/iOS/AppStore_com.AppInstitute.healthye.mobileprovision", :SIGH_UDID=>"8f0d1f5c-5199-4de8-af1c-b4b95cb02cd7", :SNAPSHOT_SCREENSHOTS_PATH=>"/Users/robwithhair/jenkins_slave/workspace/iOS Build - Release Automation/iOS/fastlane/screenshots", :IPA_OUTPUT_PATH=>"/Users/robwithhair/jenkins_slave/workspace/iOS Build - Release Automation/iOS/Framework.ipa", :DSYM_OUTPUT_PATH=>"/Users/robwithhair/jenkins_slave/workspace/iOS Build - Release Automation/iOS/Framework.app.dSYM.zip"}
[1m[31m[12:18:01]: [0m[0mCapybara::Poltergeist::TimeoutError
[1m[31m[12:18:01]: [0m[0m[31mfastlane finished with errors[0m
/Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send': Timed out waiting for response to {"name":"visit","args":["https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/955814004"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:83:in `send'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/server.rb:33:in `send'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:270:in `command'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:29:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/driver.rb:89:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.10.1/lib/fastlane_core/itunes_connect/itunes_connect_helper.rb:16:in `open_app_page'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/itunes_connect/itunes_connect_app_icon.rb:22:in `upload_app_icon!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:375:in `additional_itc_information'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:68:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:44:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/fast_file.rb:108:in `method_missing'
	from (eval):61:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
Finished: FAILURE
```

**Comment by robwithhair** [comment]
@KrauseFx any news on this issue?  Seems to be a constant issue any time anyone uses made for kids selections.
