### ISSUE TITLE
Connection reset by peer - deliver 1.1.0

### ISSUE THREAD

**Issue by The-Guru** [fastlane/deliver#358]
@KrauseFx Is there a way that deliver could reopen the connection when it is closed?
It is really painful when you are uploading 18 languages screenshots and this error happen...
You maybe could commit the changes per language uploaded?
This is the log:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:175:in `sysread_nonblock': Connection reset by peer (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:175:in `read_nonblock'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:232:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:164:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:164:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:231:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:207:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/du/du_client.rb:52:in `upload_file'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/du/du_client.rb:18:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:371:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/app_version.rb:344:in `upload_screenshot!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:36:in `block in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:23:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:23:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'

Update: Also I'm getting the "broken pipe" error as well. This is the log:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite': Broken pipe (Errno::EPIPE)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:211:in `write0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:185:in `block in write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:202:in `writing'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:184:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:184:in `send_request_with_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:130:in `exec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1404:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:232:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:164:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:164:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:231:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/client.rb:207:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/du/du_client.rb:52:in `upload_file'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/du/du_client.rb:18:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:371:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/app_version.rb:344:in `upload_screenshot!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:36:in `block in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:23:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:23:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'
```

Thanks!

**Comment by KrauseFx** [comment]
This might be very complex to build, maybe @snatchev has an idea?

**Comment by The-Guru** [comment]
At least you could expose a variable letting users set a number of languages before committing? Maybe it hasn't any sense but I don't want to split my screens uploads...
