### ISSUE TITLE
[Feature request] Validate all screenshots

### ISSUE THREAD

**Issue by alloy** [fastlane/deliver#416]
Right now I’m guessing that each screenshot is validated just before it will be uploaded, after which `deliver` exits.

```
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/app_screenshot.rb:136:in `calculate_screen_size': Unsupported screen size [640, 1137] for path './screenshots/common/1_iphone4_1.01 iphone 5.png' (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/app_screenshot.rb:39:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_screenshots.rb:67:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_screenshots.rb:67:in `block (2 levels) in collect_screenshots'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_screenshots.rb:62:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_screenshots.rb:62:in `block in collect_screenshots'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_screenshots.rb:54:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_screenshots.rb:54:in `collect_screenshots'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/runner.rb:45:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'
```

It would be nice if `deliver` could first validate all of the screenshots so that the user can have a full list of invalid screenshots and hand that full list over to the design department. Otherwise the user might risk having to go back and forth with the design department several times.

**Comment by KrauseFx** [comment]
Currently the screenshots are validated when they're collected before preparing the HTML summary page. 

[Here](https://github.com/KrauseFx/deliver/blob/master/lib/deliver/upload_screenshots.rb#L49-L71) is where the screenshots are collected. Adding a `rescue` around [this](https://github.com/KrauseFx/deliver/blob/master/lib/deliver/upload_screenshots.rb#L67) and then storing everything in a list should do the trick :+1:
