### ISSUE TITLE
Deliver attempted to continue after a failed upload

### ISSUE THREAD

**Issue by raylillywhite** [fastlane/deliver#420]
I could be misunderstanding the logs here, but it looks like the failure to upload the binary wasn't handled properly. The end of these logs seem to indicate that after Transporter failed, that it considered the upload to be successful then started looking for a build to select for the `submit_for_review` step. Fortunately, it didn't find one, but it seems like this could potentially cause a problem where the wrong build is submitted.

Here are the logs:

```
[17:41:02]: [Transporter]: DBG-X:   parameter ErrorMessage = ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
[17:41:02]: [Transporter]: DBG-X:   parameter CPUToken = 376915ac-bd03-4344-ace4-fef1783f6db1/1444696787904
[17:41:02]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=8063143d8f5370b48f0afb7bf9c3c30a.ipa}]
[17:41:02]: [Transporter]: DBG-X:   parameter FileSizes = {8063143d8f5370b48f0afb7bf9c3c30a.ipa=128949346}
[17:41:02]: [Transporter]: DBG-X:   parameter Checksums = {8063143d8f5370b48f0afb7bf9c3c30a.ipa=d513bb9c2bf9b372ff8cad6dfbad3f83}
[17:41:02]: [Transporter]: DBG-X:   parameter Errors = [ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.", ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Spruce.app/Frameworks/SpruceCore.framework' contains disallowed file 'Frameworks'."]
[17:41:02]: [Transporter]: DBG-X:   parameter ErrorCode = 1102
[17:41:02]: [Transporter]: DBG-X:   parameter Success = false
[17:41:02]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 8063143d8f5370b48f0afb7bf9c3c30a.ipa]
[17:41:02]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[17:41:02]: [Transporter Error Output]: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
[17:41:02]: [Transporter Error Output]: ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Spruce.app/Frameworks/SpruceCore.framework' contains disallowed file 'Frameworks'."
[17:41:02]: [Transporter]: DBG-X: The error code is: 1102
[17:41:02]: [Transporter]: INFO: Done performing authentication.
[17:41:02]: Transporter transfer failed.
[17:41:02]:
[17:41:02]: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Spruce.app/Frameworks/SpruceCore.framework' contains disallowed file 'Frameworks'."
[17:41:02]: Return status of iTunes Transporter was 1: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePa\nERROR ITMS-90206: "Invalid Bundle. The bundle at 'Spruce.app/Frameworks/SpruceCore.framework' contains disallowed file 'Frameworks'."to address this issue."
[17:41:02]: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Spruce.app/Frameworks/SpruceCore.framework' contains disallowed file 'Frameworks'."
Return status of iTunes Transporter was 1: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Spruce.app/HockeySDKResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of\nERROR ITMS-90206: "Invalid Bundle. The bundle at 'Spruce.app/Frameworks/SpruceCore.framework' contains disallowed file 'Frameworks'."his issue."
[17:41:02]: Finished the upload to iTunes Connect
[17:41:02]: Selecting the latest build...
[17:41:04]: []
/Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/submit_for_review.rb:59:in `select_build': Could not find build to select (RuntimeError)
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/submit_for_review.rb:5:in `submit!'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/runner.rb:72:in `submit_for_review'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/runner.rb:25:in `run'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/commands_generator.rb:84:in `run'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/gems/deliver-1.3.1/bin/deliver:5:in `<top (required)>'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/bin/deliver:23:in `load'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/bin/deliver:23:in `<main>'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rayll/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by joshsnelling** [comment]
We're also seeing this same behavior. The only difference is that we're not trying to submit a build for review, so the only impact is that the fastlane run is being reported as successful and our CI server isn't informed of the failure. This means that someone needs to manually review the logs after each run to determine if it actually worked or not, which is possible but obviously not ideal.

**Comment by Wojcik** [comment]
@raylillywhite I have the same problem with Transporter. Do you have a solution to get it work?

**Comment by raylillywhite** [comment]
No, I only recently got back around to implementing fastlane for our project, and haven't handled app store submission yet. I'll report back here if I find a solution to this

**Comment by raylillywhite** [comment]
Looking at https://github.com/fastlane/fastlane_core/blob/969f1d65da389166e0347fef5af564f74bf3a049/lib/fastlane_core/itunes_transporter.rb and the log above, it looks like at least the `ERROR_REGEX` is wrong. To me, it looks like all of the regex are wrong, because I don't know why the `>` character is at the beginning of each. If you change the `ERROR_REGEX` to `/\s*ERROR(\s|:)(.+)/`, that should work. Seems like the `>` should be removed from the beginning of each regex, but @KrauseFx might know of a reason that it's supposed to be there. I'm not in a position to test this fix right now though, so if you can test that fix and submit a PR @Wojcik, that'd be great. If not, hopefully I'll be able to get to it soon.

**Comment by Wojcik** [comment]
I've managed to upload app to appstore by removing manually CFBundleExecutable key and value from framworks Info.plist. The CFBundlePackageType key was already set to BNDL so I didn't touch it. I think this is not a deliver issue.
