### ISSUE TITLE
--submit_for_review takes a REALLY long time, then errors out

### ISSUE THREAD

**Issue by mgamber** [fastlane/deliver#447]
Using a version of deliver updated this morning, it works fine until I add --submit_for_review to the command line, then it sits there for 20 minutes or so and eventually throws an error thus:

[09:20:41]: You can tweet: "iTunes Connect #iosprocessingtime 18 minutes"
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.2/lib/spaceship/client.rb:255:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.2/lib/spaceship/tunes/tunes_client.rb:432:in `candidate_builds'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.2/lib/spaceship/tunes/app_version.rb:201:in `candidate_builds'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/submit_for_review.rb:39:in `block in select_build'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/submit_for_review.rb:38:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/submit_for_review.rb:38:in `select_build'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/submit_for_review.rb:5:in `submit!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/runner.rb:72:in `submit_for_review'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/runner.rb:25:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'

Ideas? 

Thanks!

**Comment by mgamber** [comment]
FYI, here's my deliverfile:

app_identifier "com.awesome.app" # The bundle identifier of your app
username "username@testing.com" # your Apple ID user
price_tier "0"
automatic_release true
app_rating_config_path "./ratings.json"
app_icon "./AppIcon.png"
app_review_information(
	first_name: "Tester",
	last_name: "Name",
	phone_number: "800555121",
	email_address: "me@testing.com"
)
submission_information({
  add_id_info_limits_tracking: "false",
  add_id_info_serves_ads: "false",
  add_id_info_tracks_action: "true",
  add_id_info_tracks_install: "true",
  add_id_info_uses_idfa: "false",
  content_rights_contains_third_party_content: "false",
  content_rights_has_rights: "true",
  export_compliance_available_on_french_store: "false",
  export_compliance_contains_proprietary_cryptography: "false",
  export_compliance_contains_third_party_cryptography: "false",
  export_compliance_is_exempt: "false",
  export_compliance_app_type: nil,
  export_compliance_encryption_updated: "false",
  export_compliance_compliance_required: "false",
  export_compliance_uses_encryption: "false",
  export_compliance_platform: "ios"
})

ipa "./awesomeapp.ipa"

Some data was changed to protect the innocent. The process gets kicked off with:

sudo DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" deliver --force --submit_for_review

And everything works fine up to the point of:

Selecting the latest build...

After that it spits out a bunch of "Waiting iTunes Connect processing..." and "You can tweet..." lines until it eventually times out with the above error.

I've tried various settings changes to no avail.
