### ISSUE TITLE
Temporary file name clash between different users

### ISSUE THREAD

**Issue by kaoskorobase** [fastlane/deliver#456]
`deliver` crashes when a temporary file, in this case a screenshot `PNG`, already exists in `/tmp` by a different user:

~~~~
[17:46:10]: Permission denied - /tmp/2a52955ccdc9b405fd8e9e5f084f97e9.png
~~~~

~~~~
$ ls -l /tmp/2a52955ccdc9b405fd8e9e5f084f97e9.png
-rw-r--r--  1 sk  wheel  260662 Oct 22 17:27 /tmp/2a52955ccdc9b405fd8e9e5f084f97e9.png
~~~~

Here's the backtrace:

~~~~
/Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1396:in `initialize': Permission denied - /tmp/2a52955ccdc9b405fd8e9e5f084f97e9.png (Errno::EACCES)
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1396:in `open'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1396:in `block in copy_file'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1395:in `open'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1395:in `copy_file'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1589:in `fu_each_src_dest0'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/spaceship-0.12.2/lib/spaceship/du/upload_file.rb:32:in `remove_alpha_channel'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/spaceship-0.12.2/lib/spaceship/du/upload_file.rb:15:in `from_path'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/spaceship-0.12.2/lib/spaceship/tunes/app_version.rb:343:in `upload_screenshot!'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/deliver-1.3.3/lib/deliver/upload_screenshots.rb:38:in `block in upload'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/deliver-1.3.3/lib/deliver/upload_screenshots.rb:25:in `each'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/deliver-1.3.3/lib/deliver/upload_screenshots.rb:25:in `upload'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/deliver-1.3.3/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/deliver-1.3.3/lib/deliver/runner.rb:20:in `run'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:115:in `block (2 levels) in parsing_binding'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/bin/fastlane:152:in `run'
	from /Users/jenkins/.rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.34.0/bin/fastlane:158:in `<top (required)>'
	from /Users/jenkins/.rubies/ruby-2.1.3/bin/fastlane:23:in `load'
	from /Users/jenkins/.rubies/ruby-2.1.3/bin/fastlane:23:in `<main>'
~~~~

This is with `deliver` 1.3.3 on OSX.

Are temporary file names deterministically computed from a content hash?

**Comment by kaoskorobase** [comment]
This is on a Jenkins SSH build slave btw, configured to run as user `jenkins`. The same machine is used for development, i.e. two different users may run `fastlane`. Is there a way to set a different temporary directory for deliver?
