### ISSUE TITLE
deliver stuck due to stalled transfer notification

### ISSUE THREAD

**Issue by superarts** [fastlane/deliver#464]
I'm using `fastlane` to build multiple apps, sometimes the build script stuck due to some "stalled transfer notification". This breaks the automating process so I wonder if it's possible to let deliver abort instead of hanging there please?

Parameters:
```
	deliver(
		submit_for_review: false,
		force: true,
		skip_metadata: true,
		skip_screenshots: true,
	)
```

Output:
```
[11:16:22]: ---------------------
[11:16:22]: --- Step: deliver ---
[11:16:22]: ---------------------
[11:16:22]: Login to iTunes Connect (admin@airservice.co)
[11:16:32]: Login successful

+-------------------+--------------------------------------+
|                  deliver 1.5.0 Summary                   |
+-------------------+--------------------------------------+
| username          | admin@airservice.co                  |
| app_identifier    | com.airservice.ordering.greyhound-qa |
| ipa               | Template.ipa                         |
| metadata_path     | ./fastlane/metadata                  |
| screenshots_path  | ./fastlane/screenshots               |
| skip_screenshots  | true                                 |
| app_version       | 2.4.3                                |
| skip_metadata     | true                                 |
| force             | true                                 |
| submit_for_review | false                                |
| automatic_release | false                                |
+-------------------+--------------------------------------+

[11:16:32]: Making sure the latest version on iTunes Connect matches '2.4.3' from the ipa file...
[11:16:33]: '2.4.3' is the latest version on iTunes Connect
[11:16:35]: Uploading binary to iTunes Connect
[11:16:35]: Going to upload updated app to iTunesConnect
[11:16:35]: This might take a few minutes, please don't interrupt the script
[11:16:39]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
[11:16:39]: [Transporter]: INFO: Logging configured successfully.
[11:16:39]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[11:16:39]: [Transporter]: DEBUG: Configuration refresh successful.
[11:16:39]: [Transporter]: DEBUG: Saving configuration to local path: /Users/leo/.itmstransporter/Defaults.properties
[11:16:39]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.6]
[11:16:39]: [Transporter]: INFO: OS identifier: Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[11:16:39]: [Transporter]: INFO: Memory: [JVM] 54M free, 70M total, 910M max [System] (Physical) 572M free, 8192M total (Swap) 1292M free, 3072M total
[11:16:39]: [Transporter]: INFO: Upload mode selected.
[11:16:39]: [Transporter]: INFO: Examining the package at: /tmp/1036070043.itmsp
[11:16:39]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
[11:16:39]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
[11:16:39]: [Transporter]: INFO: Gathering the list of valid files from the package ...
[11:16:39]: [Transporter]: DEBUG:   59fec68252de33db2d1f7db251b678d5.ipa will be verified by Apple's web service to determine if it is a valid file.
[11:16:39]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[11:16:39]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
[11:16:39]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
[11:16:39]: [Transporter]: INFO: Performing authentication of package 1036070043.itmsp ...
[11:16:39]: [Transporter]: DBG-X: Memory: [JVM] 33M free, 70M total, 910M max [System] (Physical) 571M free, 8192M total (Swap) 1292M free, 3072M total
[11:16:39]: [Transporter]: DBG-X: Memory: [JVM] 33M free, 70M total, 910M max [System] (Physical) 571M free, 8192M total (Swap) 1292M free, 3072M total
[11:16:39]: [Transporter]: DBG-X: Using operation named: authenticateForSession
[11:16:39]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:16:39]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:16:39]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.6
[11:16:39]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[11:16:39]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[11:16:39]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u admin@airservice.co -p **hidden value** -f /tmp/1036070043.itmsp -t Signiant -k 100000
[11:16:39]: [Transporter]: DBG-X:   parameter Username = admin@airservice.co
[11:16:39]: [Transporter]: DBG-X:   parameter Version = 1.8.6
[11:16:39]: [Transporter]: INFO: id = 20151102111639-666
[11:16:40]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:16:40]: [Transporter]: DBG-X:   parameter SessionId = CKemDBIQnHwXBk9fQZC9uWoAJlLxqg==
[11:16:40]: [Transporter]: DBG-X:   parameter SharedSecret = b0a57628-f50c-448e-8fad-5ed9903176fa
[11:16:40]: [Transporter]: DBG-X: Deflated 433 bytes to 380
[11:16:40]: [Transporter]: DBG-X: Using operation named: validateMetadata
[11:16:40]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:16:40]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:16:40]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.6
[11:16:40]: [Transporter]: DBG-X:   parameter Files = [59fec68252de33db2d1f7db251b678d5.ipa, metadata.xml]
[11:16:40]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
[11:16:40]: [Transporter]: DBG-X:   parameter MetadataChecksum = edb8939d016a0391a331e978bfefd47d
[11:16:40]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[11:16:40]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[11:16:40]: [Transporter]: DBG-X:   parameter PackageName = 1036070043.itmsp
[11:16:40]: [Transporter]: DBG-X:   parameter PackageSize = 18934459
[11:16:40]: [Transporter]: DBG-X:   parameter Throttle = 100000
[11:16:40]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u admin@airservice.co -p **hidden value** -f /tmp/1036070043.itmsp -t Signiant -k 100000
[11:16:40]: [Transporter]: DBG-X:   parameter Username = admin@airservice.co
[11:16:40]: [Transporter]: DBG-X:   parameter Version = 1.8.6
[11:16:40]: [Transporter]: INFO: id = 20151102111640-562
[11:16:41]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:16:41]: [Transporter]: DBG-X:   parameter CPUToken = 70926069-706a-4e99-aab7-17fe7c815df6/1446423401327
[11:16:41]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=59fec68252de33db2d1f7db251b678d5.ipa}]
[11:16:41]: [Transporter]: DBG-X:   parameter FileSizes = {59fec68252de33db2d1f7db251b678d5.ipa=18934026}
[11:16:41]: [Transporter]: DBG-X:   parameter Checksums = {59fec68252de33db2d1f7db251b678d5.ipa=4081bbc8e10e999e0749cc2b4a6d75ce}
[11:16:41]: [Transporter]: DBG-X:   parameter Success = true
[11:16:41]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 59fec68252de33db2d1f7db251b678d5.ipa]
[11:16:41]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[11:16:41]: [Transporter]: DBG-X:   parameter ProviderNameForToken = W6KDXC42XT
[11:16:41]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, 59fec68252de33db2d1f7db251b678d5.ipa].  These are the files that will be uploaded.
[11:16:41]: [Transporter]: INFO: Starting media analysis of assets
[11:16:41]: [Transporter]: DEBUG: Handling asset: filename=59fec68252de33db2d1f7db251b678d5.ipa,uti=com.apple.ipa,role=source,describe=true
[11:16:41]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.24
[11:16:41]: [Transporter]: DEBUG: Using path: /tmp/1036070043.itmsp/59fec68252de33db2d1f7db251b678d5.ipa
[11:16:49]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@3f947e20
[11:16:49]: [Transporter]: INFO: Asset media analysis has completed
[11:16:49]: [Transporter]: DBG-X: Memory: [JVM] 28M free, 92M total, 910M max [System] (Physical) 572M free, 8192M total (Swap) 1292M free, 3072M total
[11:16:49]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
[11:16:49]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[11:16:49]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[11:16:49]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.6
[11:16:49]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[11:16:49]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u admin@airservice.co -p **hidden value** -f /tmp/1036070043.itmsp -t Signiant -k 100000
[11:16:49]: [Transporter]: DBG-X:   parameter Username = admin@airservice.co
[11:16:49]: [Transporter]: DBG-X:   parameter Version = 1.8.6
[11:16:49]: [Transporter]: INFO: id = 20151102111649-001
[11:16:50]: [Transporter]: DBG-X: Apple's web service operation return value:
[11:16:50]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
[11:16:50]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
[11:16:50]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
[11:16:50]: [Transporter]: INFO: Using Signiant UDP transport
[11:16:50]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
[11:16:50]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
[11:16:50]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
[11:16:50]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:16:50]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
[11:16:50]: [Transporter]: INFO: Processing URL list: mxwan://sgr203.apple.com:44001/
[11:16:50]: [Transporter]: INFO: Trying UDP sgr203.apple.com/17.152.249.103:44001...
[11:16:51]: [Transporter]: INFO: Connected to UDP sgr203.apple.com/17.152.249.103:44001
[11:16:52]: [Transporter]: INFO: Authenticating
[11:16:53]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
[11:16:53]: [Transporter]: INFO: Setting up data streams
[11:16:55]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
[11:16:55]: [Transporter]: INFO: Connected using WAN accelerator
[11:16:55]: [Transporter]: INFO:      File: 2a91614c-22a8-484f-a558-5b2329ec4b701359056654428655936.txt 11/11, 100% completed
[11:16:55]: [Transporter]: DBG-X: The status for the file, 2a91614c-22a8-484f-a558-5b2329ec4b701359056654428655936.txt, is TRANSFERRED.
[11:16:56]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[11:16:57]: [Transporter]: DEBUG: An error has occurred during the upload.
[11:16:57]: [Transporter]: DEBUG: An exception has occurred: Warning: java.nio.channels.ClosedChannelException
[11:16:57]: [Transporter]: DEBUG: Transfer warning: Warning: java.nio.channels.ClosedChannelException
[11:16:57]: [Transporter]: DEBUG: Received failed transfer notification; aborting
[11:26:55]: [Transporter]: DEBUG: Received stalled transfer notification; aborting
```

**Comment by superarts** [comment]
When I break it:
```
^C./process.rb:134:in `system': Interrupt
	from ./process.rb:134:in `deploy'
	from ./process.rb:238:in `block in <main>'
	from ./process.rb:233:in `each'
	from ./process.rb:233:in `<main>'
/Users/leo/.gem/ruby/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/itunes_transporter.rb:112:in `each': Interrupt
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/itunes_transporter.rb:112:in `block in execute_transporter'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/itunes_transporter.rb:111:in `spawn'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/itunes_transporter.rb:111:in `execute_transporter'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/itunes_transporter.rb:85:in `upload'
	from /Users/leo/.gem/ruby/2.0.0/gems/deliver-1.5.0/lib/deliver/runner.rb:68:in `upload_binary'
	from /Users/leo/.gem/ruby/2.0.0/gems/deliver-1.5.0/lib/deliver/runner.rb:21:in `run'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:79:in `block (2 levels) in parsing_binding'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/lane.rb:36:in `call'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/lane.rb:36:in `call'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:46:in `execute'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/leo/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/leo/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/leo/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/leo/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/leo/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/leo/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/bin/fastlane:152:in `run'
	from /Users/leo/.gem/ruby/2.0.0/gems/fastlane-1.36.4/bin/fastlane:158:in `<top (required)>'
	from /Users/leo/.gem/ruby/2.0.0/bin/fastlane:23:in `load'
	from /Users/leo/.gem/ruby/2.0.0/bin/fastlane:23:in `<main>'
```
