### ISSUE TITLE
Deliver fails with invalid request body

### ISSUE THREAD

**Issue by s0mmer** [fastlane/deliver#572]
Using `fastlane` v. 1.57.0 and `deliver` v. 1.9.0 I get the following error when running `deliver`:

```
> fastlane appstore_metadata
[08:42:31]: -------------------------------------------------
[08:42:31]: --- Step: Verifying required fastlane version ---
[08:42:31]: -------------------------------------------------
[08:42:31]: fastlane version valid
[08:42:31]: ------------------------------
[08:42:31]: --- Step: default_platform ---
[08:42:31]: ------------------------------
[08:42:31]: Driving the lane 'ios appstore_metadata' 🚀
[08:42:31]: ---------------------
[08:42:31]: --- Step: deliver ---
[08:42:31]: ---------------------
[08:42:32]: Login to iTunes Connect (foo@foo.com)
[08:42:35]: Variable Dump:
[08:42:35]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore_metadata"}
[08:42:35]: invalid request body

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | deliver                             | 3           |
+------+-------------------------------------+-------------+

[08:42:35]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/sds/.rvm/gems/ruby-2.1.2/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] invalid request body (Spaceship::TunesClient::ITunesConnectError)
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:66:in `team_id='
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:87:in `select_team'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/spaceship-0.19.4/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/deliver-1.9.0/lib/deliver/runner.rb:15:in `login'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/deliver-1.9.0/lib/deliver/runner.rb:7:in `initialize'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/actions/deliver.rb:18:in `new'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/actions/deliver.rb:18:in `run'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:129:in `block in execute_action'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `chdir'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `execute_action'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/fast_file.rb:149:in `method_missing'
 from Fastfile:188:in `block (2 levels) in parsing_binding'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:52:in `block in execute'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `chdir'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `execute'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/command_line_handler.rb:30:in `handle'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/bin/fastlane:38:in `block (2 levels) in run'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
 from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
 from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
 from /Users/sds/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
 from /Users/sds/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
 from /Users/sds/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
 from /Users/sds/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jnbt** [comment]
Same for me if I use the `team_id` option to configure deliver.

As in: https://github.com/fastlane/deliver/blob/master/lib/deliver/options.rb#L119
