### ISSUE TITLE
Unable to activate deliver-1.10.2, because plist-3.2.0 conflicts with plist (~> 3.1.0)

### ISSUE THREAD

**Issue by soleo** [fastlane/deliver#590]
Cannot use deliver 
```

Please confirm the above values (y/n)
y
[11:59:05]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[11:59:05]: Loading up 'deliver', this might take a few seconds
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate deliver-1.10.2, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup_ios.rb:210:in `enable_deliver'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup_ios.rb:55:in `default_setup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup_ios.rb:33:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/bin/fastlane:51:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

```sh
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ deliver -v
deliver 1.10.2
```

**Comment by KrauseFx** [comment]
Can you try running `gem cleanup`? Do you use bundler?

**Comment by soleo** [comment]
I did ``gem cleanup``, but it still won't work. However, I did find a work arround way to skip this error. If I choose "n" for ``Please confirm the above values`` and skip deliver, it would work. And I would manually run ``deliver init`` in project root to create the deliverfile.

And I didn't use bundler. 

```sh
$ fastlane init
[15:34:13]: Detected iOS/Mac project in current directory...
[15:34:13]: This setup will help you get up and running in no time.
[15:34:13]: fastlane will check what tools you're already using and set up
[15:34:13]: the tool automatically for you. Have fun!
[15:34:13]: Created new folder './fastlane'.
[15:34:13]: xcrun xcodebuild -list -workspace './FancyFoodie.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com): XXXX@email.com
[15:34:22]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[15:34:22]: Starting login with user ' XXXX@email.com'

+----------------+------------------------------------------------------------------+
|                                  Detected Values                                  |
+----------------+------------------------------------------------------------------+
| Apple ID       |  XXXX@email.com                                                 |
| App Name       | Demo                                                      |
| App Identifier | com.example.demo                                     |
| Workspace      | /Users/username/projects/iOS/Demo.xcworkspace |
+----------------+------------------------------------------------------------------+

Please confirm the above values (y/n)
y
[15:34:27]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[15:34:27]: Loading up 'deliver', this might take a few seconds
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate deliver-1.10.2, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:210:in `enable_deliver'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:55:in `default_setup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:33:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/bin/fastlane:51:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by pouriaalmassi** [comment]
I'm seeing a similar error. However I'm kicking off deliver through my deploy lane. Also the backtrace is somewhat different.

```
[18:49:19]: ---------------------
[18:49:19]: --- Step: deliver ---
[18:49:19]: ---------------------
/usr/local/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate deliver-1.10.3, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems.rb:193:in `try_activate'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/actions/deliver.rb:29:in `available_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:135:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:49:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.7/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/bin/fastlane:150:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

Here is my deliver lane: 

```
desc "Deploy a new version to the App Store"
  lane :deploy do
    # Build your app - more options available
    gym(scheme: "AppName")

    deliver(
      submit_for_review: true,
      metadata_path: "./metadata",
      screenshots_path: "./screenshots",
      automatic_release: true
    )
  end
```

I have already run `gem cleanup`. @KrauseFx how does bundler relate to this issue?

**Comment by i2amsam** [comment]
@pouriaalmassi this looks like it's coming from a conflict between `deliver` and another gem, what version of `gym` are you using?  Could you try `gem install plist -v 3.2.0` ?

**Comment by AndreyNikiforov** [comment]
having the same issue with hockey action: https://github.com/fastlane/fastlane/issues/1415

**Comment by i2amsam** [comment]
@AndreyNikiforov and @pouriaalmassi could you also post your `fastlane` version?  `fastlane -v`

**Comment by i2amsam** [comment]
I think `gem uninstall plist -v 3.2.0` will fix your issue, still looking into how this conflict arose.

**Comment by AndreyNikiforov** [comment]
@i2amsam I tried FL 0.59.0 & 0.63.1 -- same result.

uninstalling plist 3.2.0 solved my issue (updated)

**Comment by soleo** [comment]
@i2amsam's solution works for me.

**Comment by i2amsam** [comment]
:+1:!

**Comment by pouriaalmassi** [comment]
@i2amsam 

```
$ fastlane -v
fastlane 1.63.0
```

```
$ gym -v
gym 1.6.1
```

**Comment by pouriaalmassi** [comment]
@i2amsam your solution worked for me. Thank you!
