### ISSUE TITLE
Error with download_metadata

### ISSUE THREAD

**Issue by maxmeyers** [fastlane/deliver#594]
I'm getting the following error from `deliver download_metadata`. Seems like it's maybe related to https://github.com/fastlane/spaceship/pull/245, but I couldn't find an issue here that mentioned it.

```
Maxs-Notebook-2:deliver maxmeyers$ deliver download_metadata
[17:56:30]: Login to iTunes Connect (***@****.com)
[17:56:33]: Login successful

+--------------------+-----------------+
|        deliver 1.10.3 Summary        |
+--------------------+-----------------+
| username           | ***@****.com   |
| app_identifier     | ********* |
| metadata_path      | ./metadata      |
| screenshots_path   | ./screenshots   |
| skip_binary_upload | false           |
| skip_screenshots   | false           |
| skip_metadata      | false           |
| force              | false           |
| submit_for_review  | false           |
| automatic_release  | false           |
+--------------------+-----------------+

Do you want to overwrite existing metadata on path '/Users/maxmeyers/deliver/metadata'? (y/n)
y
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/spaceship-0.19.0/lib/spaceship/tunes/application.rb:103:in `live_version': [!] undefined method `count' for nil:NilClass (NoMethodError)
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/spaceship-0.19.0/lib/spaceship/tunes/application.rb:121:in `latest_version'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:120:in `block (2 levels) in run'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:132:in `run'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/gems/deliver-1.10.3/bin/deliver:5:in `<top (required)>'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/bin/deliver:23:in `load'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/bin/deliver:23:in `<main>'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maxmeyers/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by maxmeyers** [comment]
This only seems to happen when the app in question does not have an unreleased version.

**Comment by lacostej** [comment]
@maxmeyers you are using an older version of spaceshp and indeed fastlane/spaceship#245 should fix it. Could you try using it locally and report if it works OK for you ?

@KrauseFx anything preventing us to merge that PR ?

**Comment by maxmeyers** [comment]
I'm not familiar with how to use these tools outside of the RubyGems context. Is there a simple way?
