### ISSUE TITLE
Error: uploaded too many Screenshots

### ISSUE THREAD

**Issue by afehners** [fastlane/deliver#597]
Trying to use deliver to update my metadata. 

I used deliver to pull down my existing metadata and then updated some screenshots.

My lane is very basic:
  lane :appstore do
    # uploads all meta data
    deliver(skip_binary_upload: true)
  end

When running this lane I get the following error on the console using fastlane 1.61.0

```
 -------------------------------------------------
[14:45:51]: --- Step: Verifying required fastlane version ---
[14:45:51]: -------------------------------------------------
[14:45:51]: fastlane version valid
[14:45:51]: ------------------------------
[14:45:51]: --- Step: default_platform ---
[14:45:51]: ------------------------------
[14:45:52]: Driving the lane 'ios App Store' 🚀
[14:45:52]: ---------------------
[14:45:52]: --- Step: deliver ---
[14:45:52]: ---------------------
[14:45:52]: Login to iTunes Connect ***************)
[14:45:55]: Login successful

+--------------------+------------------------------------+
|                 deliver 1.10.3 Summary                  |
+--------------------+------------------------------------+
| metadata_path      | ./fastlane/metadata                |
| screenshots_path   | ./fastlane/screenshots             |
| skip_binary_upload | true                               |
| skip_screenshots   | false                              |
| app_version        | 6                                  |
| skip_metadata      | false                              |
| force              | false                              |
| submit_for_review  | false                              |
| automatic_release  | false                              |
+--------------------+------------------------------------+

[14:45:56]: Making sure the latest version on iTunes Connect matches '6' from the ipa file...
[14:45:58]: '6' is the latest version on iTunes Connect
[14:45:58]: Loading './fastlane/metadata/en-GB/description.txt'...
[14:45:58]: Loading './fastlane/metadata/en-GB/keywords.txt'...
[14:45:58]: Loading './fastlane/metadata/en-GB/release_notes.txt'...
[14:45:58]: Loading './fastlane/metadata/en-GB/support_url.txt'...
[14:45:58]: Loading './fastlane/metadata/en-GB/marketing_url.txt'...
[14:45:58]: Loading './fastlane/metadata/en-GB/name.txt'...
[14:45:58]: Loading './fastlane/metadata/en-GB/privacy_url.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/description.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/keywords.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/support_url.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/name.txt'...
[14:45:58]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[14:45:58]: Loading './fastlane/metadata/copyright.txt'...
[14:45:58]: Loading './fastlane/metadata/primary_category.txt'...
[14:45:58]: Loading './fastlane/metadata/secondary_category.txt'...
[14:45:58]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[14:45:58]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[14:45:58]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[14:45:58]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[14:45:58]: Verifying the upload via the HTML file can be disabled by either adding
[14:45:58]: `force true` to your Deliverfile or using `deliver --force`
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[14:46:28]: HTML file confirmed...

[14:46:29]: Activating languages en-GB, en-US...
[14:46:32]: Uploading metadata to iTunes Connect
[14:46:35]: Successfully uploaded initial set of metadata to iTunes Connect
[14:46:36]: Starting with the upload of screenshots...
[14:46:36]: Uploading 25 screenshots for language en-GB
[14:46:36]: Uploading './fastlane/screenshots/en-GB/0_ipad_0.promo_iPad_01.png'...
[14:46:43]: Uploading './fastlane/screenshots/en-GB/1_ipad_1.promo_iPad_02.png'...
[14:46:47]: Uploading './fastlane/screenshots/en-GB/2_ipad_2.promo_iPad_03.png'...
[14:46:53]: Uploading './fastlane/screenshots/en-GB/3_ipad_3.promo_iPad_04.png'...
[14:47:00]: Uploading './fastlane/screenshots/en-GB/4_ipad_4.promo_iPad_05.png'...
[14:47:09]: Uploading './fastlane/screenshots/en-GB/iPhone3.5_01.png'...
[14:47:12]: Uploading './fastlane/screenshots/en-GB/iPhone3.5_02.png'...
[14:47:14]: Uploading './fastlane/screenshots/en-GB/iPhone3.5_03.png'...
[14:47:17]: Uploading './fastlane/screenshots/en-GB/iPhone3.5_04.png'...
[14:47:20]: Uploading './fastlane/screenshots/en-GB/iPhone3.5_05.png'...
[14:47:23]: Uploading './fastlane/screenshots/en-GB/iPhone4_01.png'...
[14:47:26]: Uploading './fastlane/screenshots/en-GB/iPhone4_02.png'...
[14:47:28]: Uploading './fastlane/screenshots/en-GB/iPhone4_03.png'...
[14:47:31]: Uploading './fastlane/screenshots/en-GB/iPhone4_04.png'...
[14:47:34]: Uploading './fastlane/screenshots/en-GB/iPhone4_05.png'...
[14:47:37]: Uploading './fastlane/screenshots/en-GB/iPhone6+_01.png'...
[14:47:42]: Uploading './fastlane/screenshots/en-GB/iPhone6+_02.png'...
[14:47:46]: Uploading './fastlane/screenshots/en-GB/iPhone6+_03.png'...
[14:47:50]: Uploading './fastlane/screenshots/en-GB/iPhone6+_04.png'...
[14:47:54]: Uploading './fastlane/screenshots/en-GB/iPhone6+_05.png'...
[14:47:59]: Uploading './fastlane/screenshots/en-GB/iPhone6_01.png'...
[14:48:02]: Uploading './fastlane/screenshots/en-GB/iPhone6_02.png'...
[14:48:05]: Uploading './fastlane/screenshots/en-GB/iPhone6_03.png'...
[14:48:08]: Uploading './fastlane/screenshots/en-GB/iPhone6_04.png'...
[14:48:11]: Uploading './fastlane/screenshots/en-GB/iPhone6_05.png'...
[14:48:14]: Saving changes
[14:48:16]: Variable Dump:
[14:48:16]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios App Store"
[14:48:16]: You have uploaded too many Screenshots for 4-inch iPhone 5 and iPod touch (5th generation) Retina displays.  The maximum is 5. You have uploaded too many Screenshots for 3.5-inch iPhone and iPod touch Retina displays.  The maximum is 5. You have uploaded too many iPad screenshots.  The maximum is 5. There is an error on the page and for 1 of your localisations.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | deliver                             | 144         |
+------+-------------------------------------+-------------+

[14:48:16]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'e64cdcd9b7dd4e36f832e318a006fdb1'
The crash report has been stored locally '/tmp/sentry_e64cdcd9b7dd4e36f832e318a006fdb1.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] You have uploaded too many Screenshots for 4-inch iPhone 5 and iPod touch (5th generation) Retina displays.  The maximum is 5. You have uploaded too many Screenshots for 3.5-inch iPhone and iPod touch Retina displays.  The maximum is 5. You have uploaded too many iPad screenshots.  The maximum is 5. There is an error on the page and for 1 of your localizations. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:347:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/app_version.rb:269:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:50:in `block in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:27:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:27:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:59:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:74:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```}

**Comment by afehners** [comment]
The cause of this error may be due to the use of a different naming convention for the new screenshots. If I manually delete the screenshots in iTunes Connect then they upload fine, and the original versions with old naming convention for another language upload fine also.

I expected the old screenshots to be removed for each device when uploading 5 new screenshots?
