### ISSUE TITLE
Upload not finish with error: "Broken pipe (Errno::EPIPE)"

### ISSUE THREAD

**Issue by dzungpv** [fastlane/deliver#599]
It not finish and show this error log:
```
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite': [!] Broken pipe (Errno::EPIPE)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:211:in `write0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:185:in `block in write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:202:in `writing'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:184:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:184:in `send_request_with_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:130:in `exec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1404:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:277:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:195:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:276:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:252:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/du/du_client.rb:52:in `upload_file'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/du/du_client.rb:18:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/tunes/tunes_client.rb:457:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/tunes/app_version.rb:348:in `upload_screenshot!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:42:in `block (2 levels) in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:29:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:29:in `block in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:27:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_screenshots.rb:27:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:59:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'
```

**Comment by vpolouchkine** [comment]
Can you please share your full setup and the parameters used when calling `deliver`?

**Comment by dzungpv** [comment]
It is the exist app on the store.
I run "deliver init" and it download all my exist image and meta, then i put the screen shot and edit meta data,  the end run "deliver".
It is the big project with about 400 images.
After this bug i think about the memory so i close all other app like Xcode (my mac with 16 GB Ram), Firefox. And the second retry it work.
And note that deliver upload all image in the screenshots folder so the process take longer. The best is only upload image not exist in the store.

**Comment by vpolouchkine** [comment]
Just to confirm, in the end, it worked for you? On the second try?

**Comment by dzungpv** [comment]
Yes, it work on the second try.

**Comment by lacostej** [comment]
EPIPE are spurious errors on the communication side. We ve modified spaceship to be more resilient about it. Version 0.21.1 should retry when having those issues,
