### ISSUE TITLE
Issue while submitting to store

### ISSUE THREAD

**Issue by vikram1234** [fastlane/deliver#603]
[04:17:13]: [Transporter]: INFO: The package: /tmp/1084529916.itmsp has been successfully uploaded.
[04:17:14]: iTunes Transporter successfully finished its job
[04:17:14]: [Transporter]: DBG-X: Returning 0
[04:17:14]: ------------------------------------------------------------------------------------------------------
[04:17:14]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[04:17:14]: ------------------------------------------------------------------------------------------------------
[04:17:14]: Finished the upload to iTunes Connect
[04:17:15]: Selecting the latest build...
[04:17:16]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:17:48]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:18:20]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:18:51]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:19:22]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:19:54]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:20:26]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:20:57]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:21:29]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:22:01]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:22:32]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:22:32]: 
[04:22:32]: You can tweet: "iTunes Connect #iosprocessingtime 5 minutes"
[04:23:04]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:23:04]: 
[04:23:04]: You can tweet: "iTunes Connect #iosprocessingtime 6 minutes"
[04:23:35]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:23:35]: 
[04:23:35]: You can tweet: "iTunes Connect #iosprocessingtime 6 minutes"
[04:24:16]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:24:16]: 
[04:24:16]: You can tweet: "iTunes Connect #iosprocessingtime 7 minutes"
[04:24:48]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:24:48]: 
[04:24:48]: You can tweet: "iTunes Connect #iosprocessingtime 8 minutes"
[04:25:23]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:25:23]: 
[04:25:23]: You can tweet: "iTunes Connect #iosprocessingtime 8 minutes"
[04:25:55]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:25:55]: 
[04:25:55]: You can tweet: "iTunes Connect #iosprocessingtime 9 minutes"
[04:26:27]: Selecting build 1.0 (1.0)...
[04:26:28]: Successfully selected build
[04:26:28]: Submitting the app for review...
[04:26:31]: Variable Dump:
[04:26:31]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :CERT_FILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/V52DKXD3X5.cer", :CERT_CERTIFICATE_ID=>"V52DKXD3X5", :SIGH_PROFILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision"], :SIGH_UDID=>"4c3eb709-c79e-4f84-9049-04eaecd1ee41", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.ipa", :DSYM_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/viki/Library/Developer/Xcode/Archives/2016-02-26/proapps 2016-02-26 04.13.27.xcarchive"}
[04:26:31]: Re-validating version produced errors.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cert                                | 4           |
| 4    | sigh                                | 6           |
| 5    | pem                                 | 1           |
| 6    | update_project_provisioning         | 11          |
| 7    | gym                                 | 71          |
| 8    | deliver                             | 718         |
+------+-------------------------------------+-------------+

[04:26:32]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'baf21134185e391a2e55b74cf9207f9d'
The crash report has been stored locally '/tmp/sentry_baf21134185e391a2e55b74cf9207f9d.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] Re-validating version produced errors. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:683:in `send_app_submission'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/app_submission.rb:127:in `complete!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/submit_for_review.rb:25:in `submit!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:87:in `submit_for_review'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:126:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
[sentry_baf21134185e391a2e55b74cf9207f9d.json.zip](https://github.com/fastlane/deliver/files/147548/sentry_baf21134185e391a2e55b74cf9207f9d.json.zip)

**Comment by vikram1234** [comment]
Also error while submitting to testflight - 

[19:25:47]: [Transporter]: DBG-X: Returning 0
[19:25:47]: ------------------------------------------------------------------------------------------------------
[19:25:47]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[19:25:47]: ------------------------------------------------------------------------------------------------------
[19:25:47]: Successfully uploaded the new binary to iTunes Connect
[19:25:47]: Waiting for iTunes Connect to process the new build
[19:26:20]: Waiting for iTunes Connect to process the new build
[19:26:52]: Waiting for iTunes Connect to process the new build
[19:27:24]: Waiting for iTunes Connect to process the new build
[19:27:56]: Waiting for iTunes Connect to process the new build
[19:28:29]: Waiting for iTunes Connect to process the new build
[19:29:01]: Waiting for iTunes Connect to process the new build
[19:29:35]: Waiting for iTunes Connect to process the new build
[19:30:07]: Waiting for iTunes Connect to process the new build
[19:30:40]: Waiting for iTunes Connect to process the new build
[19:31:12]: Waiting for iTunes Connect to process the new build
[19:31:45]: Waiting for iTunes Connect to process the new build
[19:32:20]: Waiting for iTunes Connect to process the new build
[19:32:52]: Waiting for iTunes Connect to process the new build
[19:33:24]: Waiting for iTunes Connect to process the new build
[19:33:57]: Waiting for iTunes Connect to process the new build
[19:34:30]: Waiting for iTunes Connect to process the new build
[19:35:03]: Waiting for iTunes Connect to process the new build
[19:35:35]: Waiting for iTunes Connect to process the new build
[19:36:08]: Waiting for iTunes Connect to process the new build
[19:36:43]: Waiting for iTunes Connect to finish processing the new build (1.1 - 1.1)
[19:37:13]: Successfully finished processing the build
[19:37:13]: You can now tweet: 
[19:37:13]: iTunes Connect #iosprocessingtime 11 minutes
[19:37:13]: Distributing new build to testers

#######################################################################
# pilot 1.4.1 is available. You are on 1.3.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update pilot'.
#######################################################################

1.4.1 Bugfix
Fixed an issue with uploading iOS builds

1.4.0 New Features
- You can now find, add and remove multiple testers at once
(thanks Jacob Aleksynas)
- Improved build upload
- Added automatic submission of external builds (thanks @tmm1)
- Improved input parsing
- Added more columns to the user list (thanks @knutigro)

Update using 'sudo gem update pilot'
[19:37:16]: Variable Dump:
[19:37:16]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :IPA_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.ipa", :DSYM_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/viki/Library/Developer/Xcode/Archives/2016-02-26/proapps 2016-02-26 19.23.42.xcarchive"}
[19:37:16]: operation_failed

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 55          |
| 4    | pilot                               | 766         |
+------+-------------------------------------+-------------+

[19:37:16]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '49299a0a76a89c3ef87b856a0af1ce34'
The crash report has been stored locally '/tmp/sentry_49299a0a76a89c3ef87b856a0af1ce34.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] operation_failed (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:526:in `update_build_trains!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:110:in `distribute_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:22:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:113:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by vikram1234** [comment]
Deliver to Pialot worked, please ignore that part.

**Comment by vpolouchkine** [comment]
Can you please update to the latest versions? Also, if you could share your Fastfile that would be great.

**Comment by vikram1234** [comment]
lane :appstore do

    #Production build cert, pem and prov profiles
    cert(output_path: "./util/", team_id: "637M7XTA7S")
    sigh(force: true, provisioning_name: ENV["identifer"]+"-prod", output_path: "./util/",app_identifier:ENV["identifer"], team_id: "637M7XTA7S")
    pem(
      app_identifier: ENV["identifer"],
      output_path: "./util/",
      pem_name: "cert.pem",
      p12_password: "abc"
    )

    update_project_provisioning(
      xcodeproj: "proapps.xcodeproj",
      profile: "./util/AppStore_"+ENV["identifer"]+".mobileprovision", # optional if you use sigh
      #target_filter: ".*WatchKit Extension.*", # matches name or type of a target
      build_configuration: "Release"
    )

    gym(
      scheme: ENV["scheme"],
      #export_method: "ad-hoc",
      export_method: "enterprise",
      clean: true,
      #provisioning_profile_path: "./util/AppStore_"+ENV["identifer"]+".mobileprovision",
      use_legacy_build_api: true,
    #  output_name: ENV["ipaname"],
      output_directory: "./util/",
      silent: true
    )

    #Take snapshots
   if ENV["takescreenshot"] == "true"
     snapshot(
       scheme: ENV["scheme"]
     )
   end

   #Deliver to test flight if marked
    if ENV["testflight"] == "true"
      pilot(
        ipa: "./util/"+ENV["ipaname"],
        #skip_submission: true,
      )
    end

    deliver(
      force: true,
       app_identifier: ENV["identifer"],
       app_icon: "./fastlane/metadata/delivericon.png",
       ipa: "./util/"+ENV["ipaname"],
       submit_for_review: true,
       automatic_release: false,
       force: true,
       #description: "This is test app",
      metadata_path: "./fastlane/metadata/",
       app_review_information: ({
        first_name: "removed",
        last_name: "removed",
        phone_number: "+43 123123123",
        email_address: "removed",
        demo_user: "demoUser",
        notes: "This is app release notes",
        demo_password: "demoPass"
      })
    )


    # frameit
  end

**Comment by vikram1234** [comment]
Deliver version -  1.10.3

**Comment by vikram1234** [comment]
@vpolouchkine - Still same error, is this latest version? 1.10.3?

[11:10:45]: Variable Dump:
[11:10:45]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :BUILD_NUMBER=>"3", :VERSION_NUMBER=>"2.2.0", :CERT_FILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/V52DKXD3X5.cer", :CERT_CERTIFICATE_ID=>"V52DKXD3X5", :SIGH_PROFILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision"], :SIGH_UDID=>"824bef3e-a45f-4bbf-9a96-04cc2465b962", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.ipa", :DSYM_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/viki/Library/Developer/Xcode/Archives/2016-02-27/proapps 2016-02-27 10.55.55.xcarchive"}
[11:10:45]: Re-validating version produced errors.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 4    | increment_version_number            | 1           |
| 5    | update_info_plist                   | 0           |
| 6    | update_app_identifier               | 0           |
| 7    | cert                                | 21          |
| 8    | sigh                                | 7           |
| 9    | pem                                 | 1           |
| 10   | update_project_provisioning         | 7           |
| 11   | gym                                 | 104         |
| 12   | deliver                             | 794         |
+------+-------------------------------------+-------------+

[11:10:45]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'bc651a9f62dc7b8bcebef239780c2ba3'
The crash report has been stored locally '/tmp/sentry_bc651a9f62dc7b8bcebef239780c2ba3.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] Re-validating version produced errors. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:683:in `send_app_submission'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/app_submission.rb:127:in `complete!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/submit_for_review.rb:25:in `submit!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:87:in `submit_for_review'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:140:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by vpolouchkine** [comment]
Yup, but looks like you're running an outdated version of `spaceship`. Can you please run `sudo gem update spaceship` and try again?

**Comment by vikram1234** [comment]
@vpolouchkine - thanks for your reply, i still have same issue. 

[23:15:33]: You can tweet: "iTunes Connect #iosprocessingtime 16 minutes"
[23:16:06]: Selecting build 2.3.0 (3)...
[23:16:08]: Successfully selected build
[23:16:08]: Submitting the app for review...
[23:16:12]: Variable Dump:
[23:16:12]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :BUILD_NUMBER=>"3", :VERSION_NUMBER=>"2.3.0", :CERT_FILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/V52DKXD3X5.cer", :CERT_CERTIFICATE_ID=>"V52DKXD3X5", :SIGH_PROFILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision"], :SIGH_UDID=>"2a801250-9711-4220-9c27-6b913bb53cd1", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.ipa", :DSYM_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/viki/Library/Developer/Xcode/Archives/2016-02-29/proapps 2016-02-29 22.55.26.xcarchive"}
[23:16:12]: Re-validating version produced errors.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 4    | increment_version_number            | 2           |
| 5    | update_info_plist                   | 0           |
| 6    | update_app_identifier               | 0           |
| 7    | cert                                | 20          |
| 8    | sigh                                | 8           |
| 9    | pem                                 | 4           |
| 10   | update_project_provisioning         | 5           |
| 11   | gym                                 | 82          |
| 12   | deliver                             | 1170        |
+------+-------------------------------------+-------------+

[23:16:12]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'a4d715b5bd416cd8d078778bbcd2cc0f'
The crash report has been stored locally '/tmp/sentry_a4d715b5bd416cd8d078778bbcd2cc0f.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] Re-validating version produced errors. (Spaceship::TunesClient::ITunesConnectError)

**Comment by vpolouchkine** [comment]
Looks like you have an issue with the .ipa version and the version you reported.
